[package]
name = "eth-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2", features = ["full"] }
dotenv = "0.15.0"
futures = "0.3.30"
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.15"
